const STORAGE_KEY = 'morrow-tasks-v1';
const THEME_KEY = 'morrow-theme';
const messages = ['Nice.', 'One less thing.', 'That feels good.', 'A little lighter.', 'All clear.'];
const categories = ['work', 'family', 'finances', 'personal', 'errands', 'learning', 'health', 'leisure'];
const state = { tasks: loadTasks(), view: 'all', editingId: null, draggedId: null, toastTimer: null, messageIndex: 0, calendarDate: new Date() };
const $ = (selector) => document.querySelector(selector);
const els = { taskList: $('#taskList'), empty: $('#emptyState'), addForm: $('#addForm'), input: $('#taskInput'), toast: $('#toast'), toastMessage: $('#toastMessage'), undo: $('#undoButton') };

function loadTasks() { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(parsed) ? parsed.filter(t => t && t.id && t.title) : []; } catch { return []; } }
function saveTasks() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.tasks)); }
function uid() { return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function dateKey(value = new Date()) { const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function formatDate(value) { if (!value) return ''; const d = new Date(`${value}T12:00:00`); return Number.isNaN(d.getTime()) ? '' : d.toLocaleDateString(undefined, { month:'short', day:'numeric' }); }
function formatCompleted(value) { const d = new Date(value); return Number.isNaN(d.getTime()) ? 'Completed recently' : `Completed ${d.toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}`; }
function categoryName(value) { return value ? value[0].toUpperCase() + value.slice(1) : 'Personal'; }
function categoryClass(value) { return categories.includes(value) ? `category-${value}` : 'category-personal'; }
function activeTasks() { return state.tasks.filter(t => !t.completed); }
function visibleTasks() { const active = activeTasks(); if (state.view === 'history') return state.tasks.filter(t => t.completed).sort((a,b) => new Date(b.completedAt) - new Date(a.completedAt)); if (state.view === 'today') return active.filter(t => t.dueDate === dateKey()); if (state.view === 'upcoming') return active.filter(t => t.dueDate && t.dueDate > dateKey()).sort((a,b) => a.dueDate.localeCompare(b.dueDate)); return active; }
function render() {
  const tasks = visibleTasks(); const active = activeTasks(); const completed = state.tasks.filter(t => t.completed).length;
  $('#allCount').textContent = active.length; $('#todayCount').textContent = active.filter(t => t.dueDate === dateKey()).length; $('#upcomingCount').textContent = active.filter(t => t.dueDate && t.dueDate > dateKey()).length; $('#historyCount').textContent = completed; $('#taskTotal').textContent = `${state.tasks.length} ${state.tasks.length === 1 ? 'task' : 'tasks'} in all`;
  const titles = { all:['YOUR TASKS','Today, gently'], today:['DUE TODAY','A little focus'], upcoming:['ON THE HORIZON','When you’re ready'], history:['COMPLETED','You’ve done a lot'], calendar:['CALENDAR','Plan your month'] }; const [kicker,title] = titles[state.view] || titles.all; $('#sectionKicker').textContent = kicker; $('#sectionTitle').textContent = title;
  $('#progressWrap').hidden = state.view === 'history'; const progressTasks = state.view === 'today' ? state.tasks.filter(t => t.dueDate === dateKey()) : state.tasks; const doneForView = progressTasks.filter(t => t.completed).length; const totalForView = progressTasks.length; const progressPercent = totalForView ? Math.round(doneForView / totalForView * 100) : 0; $('#progressText').textContent = state.view === 'history' ? '' : totalForView ? `${doneForView} of ${totalForView} completed` : 'Nothing to complete'; $('#progressBar').style.width = `${progressPercent}%`; $('.progress-track').setAttribute('aria-valuenow', progressPercent);
  document.querySelectorAll('.view-tab').forEach(tab => tab.classList.toggle('active', tab.dataset.view === state.view));
  els.taskList.innerHTML = tasks.map(taskCard).join(''); els.empty.hidden = tasks.length > 0; if (!tasks.length) els.empty.innerHTML = emptyMarkup();
  if (state.view === 'history' || tasks.length === 0) els.addForm.hidden = state.view === 'history'; else els.addForm.hidden = false;
  const calendarActive = state.view === 'calendar'; document.querySelector('.task-section').hidden = calendarActive; $('#calendarSection').hidden = !calendarActive; if (calendarActive) renderCalendar();
}
function renderCalendar() { const year = state.calendarDate.getFullYear(); const month = state.calendarDate.getMonth(); $('#calendarTitle').textContent = state.calendarDate.toLocaleDateString(undefined,{month:'long',year:'numeric'}); const firstDay = new Date(year, month, 1); const offset = (firstDay.getDay() + 6) % 7; const daysInMonth = new Date(year, month + 1, 0).getDate(); const cells = []; const weekdays = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']; weekdays.forEach(day => cells.push(`<div class="calendar-weekday">${day}</div>`)); for (let i = 0; i < 42; i++) { const dayNumber = i - offset + 1; const date = new Date(year, month, dayNumber); const key = dateKey(date); const inMonth = date.getMonth() === month; const today = key === dateKey(); const dayTasks = state.tasks.filter(task => task.dueDate === key); const taskMarkup = dayTasks.slice(0,3).map(task => `<button class="calendar-task ${categoryClass(task.category)} ${task.completed ? 'completed' : ''}" data-calendar-task="${task.id}" type="button" title="${escapeAttr(task.title)}"><span class="urgency-marker ${task.priority || 'normal'}"></span><span class="calendar-task-title">${escapeHtml(task.title)}</span></button>`).join(''); const more = dayTasks.length > 3 ? `<span class="calendar-more">+${dayTasks.length - 3} more</span>` : ''; cells.push(`<div class="calendar-day ${inMonth ? '' : 'other-month'} ${today ? 'is-today' : ''}"><div class="calendar-date"><span>${date.getDate()}</span></div><div class="calendar-task-list">${taskMarkup}${more}</div></div>`); } $('#calendarGrid').innerHTML = cells.join(''); }
function emptyMarkup() { if (state.view === 'history') return `<div class="empty-icon">✦</div><h3>Your history is waiting.</h3><p>Completed tasks will find their way here.</p>`; if (state.view === 'today') return `<div class="empty-icon">☀</div><h3>A clear day ahead.</h3><p>Nothing due today. Enjoy the breathing room.</p>`; if (state.view === 'upcoming') return `<div class="empty-icon">⌁</div><h3>Nothing on the horizon.</h3><p>Add a due date when something needs a little room.</p>`; return `<div class="empty-icon">✳</div><h3>A quiet little list.</h3><p>Add something small to get started.</p>`; }
function taskCard(task) { const isHistory = task.completed; const priority = task.priority || 'normal'; const category = categories.includes(task.category) ? task.category : 'personal'; const editing = state.editingId === task.id; const due = formatDate(task.dueDate); const overdue = task.dueDate && task.dueDate < dateKey() && !isHistory; const categoryOptions = categories.map(item => `<option value="${item}" ${item===category?'selected':''}>${categoryName(item)}</option>`).join(''); return `<article class="task-card ${isHistory ? 'history-card' : ''} ${editing ? 'editing' : ''}" draggable="${!isHistory && !editing}" data-id="${task.id}"><span class="drag-handle" aria-hidden="true">⠿</span>${isHistory ? '<span class="check-button" aria-hidden="true">✓</span>' : `<button class="check-button" data-action="complete" aria-label="Complete ${escapeHtml(task.title)}"></button>`}<div class="task-content">${editing ? `<input class="task-title" data-edit-input value="${escapeAttr(task.title)}" maxlength="140" aria-label="Edit task title" /><div class="edit-fields"><label>Priority <select data-edit-priority aria-label="Priority"><option value="normal" ${priority==='normal'?'selected':''}>Normal</option><option value="important" ${priority==='important'?'selected':''}>Important</option><option value="urgent" ${priority==='urgent'?'selected':''}>Urgent</option></select></label><label>Category <select data-edit-category aria-label="Category">${categoryOptions}</select></label><label>Due <input type="date" data-edit-date value="${escapeAttr(task.dueDate || '')}" aria-label="Due date" /></label></div>` : `<p class="task-title">${escapeHtml(task.title)}</p>`}<div class="task-meta"><span class="priority-label ${priority}">${priority[0].toUpperCase()+priority.slice(1)}</span><span class="category-label ${categoryClass(category)}">${categoryName(category)}</span>${due ? `<span>·</span><span class="due-date ${overdue ? 'overdue' : ''}">${overdue ? 'Overdue · ' : 'Due '}${due}</span>` : ''}${isHistory ? `<span>·</span><span>${formatCompleted(task.completedAt)}</span>` : ''}</div></div><div class="task-actions">${editing ? `<button class="small-button" data-action="save">Save</button><button class="small-button" data-action="cancel">Cancel</button>` : isHistory ? `<button class="small-button restore-button" data-action="restore">Restore</button>` : `<button class="small-button" data-action="edit">Edit</button>`}</div></article>`; }
function escapeHtml(s) { return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c])); }
function escapeAttr(s) { return escapeHtml(s); }
function updateTask(id, changes) { const task = state.tasks.find(t => t.id === id); if (task) Object.assign(task, changes); saveTasks(); render(); }
function completeTask(id) { const task = state.tasks.find(t => t.id === id); if (!task) return; const card = document.querySelector(`[data-id="${CSS.escape(id)}"]`); task.completed = true; task.completedAt = new Date().toISOString(); saveTasks(); if (card) { card.insertAdjacentHTML('afterbegin', '<span class="confetti-piece"></span>'.repeat(8)); card.classList.add('completing'); setTimeout(() => { render(); showToast(messages[state.messageIndex++ % messages.length], task); }, 520); } else { render(); showToast(messages[state.messageIndex++ % messages.length], task); } }
function showToast(message, task) { clearTimeout(state.toastTimer); els.toastMessage.textContent = message; els.toast.classList.add('visible'); els.undo.onclick = () => { if (task) { task.completed = false; task.completedAt = null; saveTasks(); render(); } hideToast(); }; state.toastTimer = setTimeout(hideToast, 5000); }
function hideToast() { els.toast.classList.remove('visible'); }

els.addForm.addEventListener('submit', e => { e.preventDefault(); const title = els.input.value.trim(); if (!title) { els.input.focus(); return; } state.tasks.unshift({ id:uid(), title, priority:'normal', category:'personal', dueDate:'', completed:false, createdAt:new Date().toISOString(), completedAt:null }); saveTasks(); els.input.value=''; render(); els.input.focus(); });
document.querySelector('.view-nav').addEventListener('click', e => { const tab = e.target.closest('.view-tab'); if (!tab) return; state.view = tab.dataset.view; state.editingId = null; hideToast(); render(); });
els.taskList.addEventListener('click', e => { const action = e.target.closest('[data-action]')?.dataset.action; const card = e.target.closest('.task-card'); if (!action || !card) return; const task = state.tasks.find(t => t.id === card.dataset.id); if (!task) return; if (action === 'complete') completeTask(task.id); if (action === 'restore') updateTask(task.id,{completed:false,completedAt:null}); if (action === 'edit') { state.editingId = task.id; render(); setTimeout(() => document.querySelector('[data-edit-input]')?.focus(),0); } if (action === 'cancel') { state.editingId=null; render(); } if (action === 'save') { const input = card.querySelector('[data-edit-input]'); const title = input.value.trim(); if (title) updateTask(task.id,{title,priority:card.querySelector('[data-edit-priority]').value,category:card.querySelector('[data-edit-category]').value,dueDate:card.querySelector('[data-edit-date]').value}); state.editingId=null; render(); } });
els.taskList.addEventListener('keydown', e => { if (!e.target.matches('[data-edit-input]')) return; if (e.key === 'Escape') { state.editingId=null; render(); } if (e.key === 'Enter') e.target.closest('.task-card').querySelector('[data-action="save"]').click(); });
els.taskList.addEventListener('dragstart', e => { const card=e.target.closest('.task-card'); if (!card || state.view !== 'all') return; state.draggedId=card.dataset.id; card.classList.add('dragging'); e.dataTransfer.effectAllowed='move'; });
els.taskList.addEventListener('dragover', e => { e.preventDefault(); const target=e.target.closest('.task-card'); if (!target || target.dataset.id===state.draggedId) return; const dragged=state.tasks.find(t=>t.id===state.draggedId), over=state.tasks.find(t=>t.id===target.dataset.id); if (!dragged || !over || dragged.completed || over.completed) return; const from=state.tasks.indexOf(dragged), to=state.tasks.indexOf(over); state.tasks.splice(from,1); state.tasks.splice(to,0,dragged); render(); });
els.taskList.addEventListener('dragend', () => { state.draggedId=null; saveTasks(); });
$('#calendarSection').addEventListener('click', e => { const control = e.target.closest('[data-calendar-action]'); if (control) { const action = control.dataset.calendarAction; if (action === 'previous') state.calendarDate = new Date(state.calendarDate.getFullYear(), state.calendarDate.getMonth() - 1, 1); if (action === 'next') state.calendarDate = new Date(state.calendarDate.getFullYear(), state.calendarDate.getMonth() + 1, 1); if (action === 'today') state.calendarDate = new Date(); render(); return; } const taskButton = e.target.closest('[data-calendar-task]'); if (!taskButton) return; const task = state.tasks.find(item => item.id === taskButton.dataset.calendarTask); if (!task) return; state.view = task.completed ? 'history' : 'all'; state.editingId = task.id; render(); setTimeout(() => { const card = document.querySelector(`[data-id="${CSS.escape(task.id)}"]`); card?.scrollIntoView({ behavior:'smooth', block:'center' }); document.querySelector('[data-edit-input]')?.focus(); }, 0); });
$('#themeToggle').addEventListener('click', () => { document.body.classList.toggle('dark'); const dark=document.body.classList.contains('dark'); localStorage.setItem(THEME_KEY,dark?'dark':'light'); $('#themeIcon').textContent=dark?'☀':'☾'; $('#themeToggle').setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme'); });
const savedTheme=localStorage.getItem(THEME_KEY); if (savedTheme === 'dark') { document.body.classList.add('dark'); $('#themeIcon').textContent='☀'; $('#themeToggle').setAttribute('aria-label','Switch to light theme'); }
$('#todayLabel').textContent = new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}); render();
